### ISSUE TITLE
error with neoforge 1.21.1

### ISSUE THREAD

**Issue by VaporeonScripts** [ochotonida/trofers#23]
at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210) [bootstraplauncher-2.0.2.jar:?] {}
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) [bootstraplauncher-2.0.2.jar:?] {}
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?] {}
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {re:mixin}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67) [ForgeWrapper-prism-2024-02-29.jar:prism-2024-02-29] {}
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) [NewLaunch.jar:?] {}
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?] {}
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?] {}
[10:40:30] [Render thread/ERROR] [Mod Menu | ModsScreen/]: Error from mod 'trofers'
java.lang.AbstractMethodError: Receiver class trofers.neoforge.TrofersNeoForge$$Lambda/0x000076a5b63e5c70 does not define or inherit an implementation of the resolved method 'abstract net.minecraft.client.gui.screens.Screen createScreen(net.neoforged.fml.ModContainer, net.minecraft.client.gui.screens.Screen)' of interface net.neoforged.neoforge.client.gui.IConfigScreenFactory.

**Comment by ochotonida** [comment]
Sorry for the long wait. Version 8.0.1 should fix the issue.

**Comment by VaporeonScripts** [comment]
No worries ig
